apiVersion: skaffold/v4beta3
kind: Config

manifests:
  kustomize:
    paths:
      - infrastructure/kubernetes/overlays/development

deploy:
  statusCheckDeadlineSeconds: 900
  kubectl: {}

build:
  local:
    push: false
    useBuildkit: true

  artifacts:

    - image: delivery/notification
      context: .
      docker:
        dockerfile: services/notification-service/Dockerfile
      sync:
        manual:
          - src: "services/notification-service/src/**/*.ts"
            dest: /usr/src/app/services/notification-service/src
          - src: "protos/**/*.proto"
            dest: /usr/src/app/protos
          - src: 'packages/ts/dist/**/*.js'
            dest: /usr/src/app/packages/ts/dist

    - image: delivery/realtime
      context: .
      docker:
        dockerfile: services/realtime-service/Dockerfile
      sync:
        manual:
          - src: "services/realtime-service/src/**/*.ts"
            dest: /usr/src/app/services/realtime-service/src
          - src: "protos/**/*.proto"
            dest: /usr/src/app/protos
          - src: 'packages/ts/dist/**/*.js'
            dest: /usr/src/app/packages/ts/dist

    - image: delivery/search
      context: .
      docker:
        dockerfile: services/search-service/Dockerfile

    - image: delivery/media
      context: .
      docker:
        dockerfile: services/media-service/Dockerfile

    - image: delivery/user
      context: .
      docker:
        dockerfile: services/user-service/Dockerfile
      sync:
        manual:
          - src: 'services/user-service/src/**/*.ts'
            dest: /usr/src/app/services/user-service/src
          - src: "protos/**/*.proto"
            dest: /usr/src/app/protos
          - src: 'packages/ts/dist/**/*.js'
            dest: /usr/src/app/packages/ts/dist

    - image: delivery/delivery
      context: .
      docker:
        dockerfile: services/delivery-service/Dockerfile
      sync:
        manual:
          - src: 'services/delivery-service/src/**/*.ts'
            dest: /usr/src/app/services/delivery-service/src
          - src: "protos/**/*.proto"
            dest: /usr/src/app/protos
          - src: 'packages/ts/dist/**/*.js'
            dest: /usr/src/app/packages/ts/dist

    - image: delivery/api-gateway
      context: .
      docker:
        dockerfile: services/api-gateway/Dockerfile
      sync:
        manual:
          - src: "services/api-gateway/src/**/*.ts"
            dest: /usr/src/app/services/api-gateway/src
          - src: "protos/**/*.proto"
            dest: /usr/src/app/protos
          - src: 'packages/ts/dist/**/*.js'
            dest: /usr/src/app/packages/ts/dist


profiles:
  - name: test
    manifests:
      kustomize:
        paths:
          - infrastructure/kubernetes/overlays/test
  - name: production
    manifests:
      kustomize:
        paths:
          - infrastructure/kubernetes/overlays/production

portForward:

  - resourceType: service
    resourceName: api-gateway-srv
    port: 4000
    localPort: 4000
