apiVersion: v1
kind: Service
metadata:
  name: media-srv
  namespace: default
  labels:
    app: media-service
spec:
  selector:
    app: media-service
  ports:
  - name: grpc
    port: 4002
    targetPort: 4002
    protocol: TCP
  - name: metrics
    port: 9102
    targetPort: 9102
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: media-service-sa
  namespace: default
