apiVersion: skaffold/v4beta3
kind: Config

manifests:
  rawYaml:
    - ./k8s/*

deploy:
  statusCheckDeadlineSeconds: 1800

build:
  local:
    push: false

  artifacts:

    - image: delivery/api-gateway
      context: .
      docker:
        dockerfile: services/api-gateway/Dockerfile
      sync:
        manual:
          - src: "services/api-gateway/src/**/*.ts"
            dest: /usr/src/app/services/api-gateway/src
          - src: "protos/**/*.proto"
            dest: /usr/src/app/protos

    - image: delivery/user
      context: .
      docker:
        dockerfile: services/user-service/Dockerfile
      sync:
        manual:
          - src: 'services/user-service/src/**/*.ts'
            dest: /usr/src/app/services/user-service/src
          - src: "protos/**/*.proto"
            dest: /usr/src/app/protos
          - src: 'packages/ts/dist/**/*.js'
            dest: /usr/src/app/packages/ts/dist

    - image: delivery/media
      context: .
      docker:
        dockerfile: services/media-service/Dockerfile

portForward:
  - resourceType: service
    resourceName: api-gateway-srv
    port: 4000
    localPort: 4000
    
  - resourceType: service
    resourceName: localstack-srv
    port: 4566
    localPort: 4566

