// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/media/v1/media.proto

package mediav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUploadSessionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // injected by gRPC interceptor from x-user-id header
	FileName       string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ContentType    string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Size           int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Checksum       string                 `protobuf:"bytes,5,opt,name=checksum,proto3" json:"checksum,omitempty"`                       // optional client SHA-256 hex
	DeliveryId     string                 `protobuf:"bytes,6,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"` // optional
	IdempotencyKey string                 `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateUploadSessionRequest) Reset() {
	*x = CreateUploadSessionRequest{}
	mi := &file_proto_media_v1_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUploadSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUploadSessionRequest) ProtoMessage() {}

func (x *CreateUploadSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUploadSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateUploadSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUploadSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateUploadSessionRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *CreateUploadSessionRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *CreateUploadSessionRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *CreateUploadSessionRequest) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *CreateUploadSessionRequest) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *CreateUploadSessionRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type CreateUploadSessionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MediaId        string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	UploadId       string                 `protobuf:"bytes,2,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	S3UploadId     string                 `protobuf:"bytes,3,opt,name=s3_upload_id,json=s3UploadId,proto3" json:"s3_upload_id,omitempty"`
	PresignedParts []*PresignedPart       `protobuf:"bytes,4,rep,name=presigned_parts,json=presignedParts,proto3" json:"presigned_parts,omitempty"`
	PartSize       int64                  `protobuf:"varint,5,opt,name=part_size,json=partSize,proto3" json:"part_size,omitempty"`
	TotalParts     int32                  `protobuf:"varint,6,opt,name=total_parts,json=totalParts,proto3" json:"total_parts,omitempty"`
	ExpiresAt      int64                  `protobuf:"varint,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // unix seconds
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateUploadSessionResponse) Reset() {
	*x = CreateUploadSessionResponse{}
	mi := &file_proto_media_v1_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUploadSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUploadSessionResponse) ProtoMessage() {}

func (x *CreateUploadSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUploadSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateUploadSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUploadSessionResponse) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *CreateUploadSessionResponse) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *CreateUploadSessionResponse) GetS3UploadId() string {
	if x != nil {
		return x.S3UploadId
	}
	return ""
}

func (x *CreateUploadSessionResponse) GetPresignedParts() []*PresignedPart {
	if x != nil {
		return x.PresignedParts
	}
	return nil
}

func (x *CreateUploadSessionResponse) GetPartSize() int64 {
	if x != nil {
		return x.PartSize
	}
	return 0
}

func (x *CreateUploadSessionResponse) GetTotalParts() int32 {
	if x != nil {
		return x.TotalParts
	}
	return 0
}

func (x *CreateUploadSessionResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type PresignedPart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartNumber    int32                  `protobuf:"varint,1,opt,name=part_number,json=partNumber,proto3" json:"part_number,omitempty"`
	PresignedUrl  string                 `protobuf:"bytes,2,opt,name=presigned_url,json=presignedUrl,proto3" json:"presigned_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresignedPart) Reset() {
	*x = PresignedPart{}
	mi := &file_proto_media_v1_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresignedPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignedPart) ProtoMessage() {}

func (x *PresignedPart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignedPart.ProtoReflect.Descriptor instead.
func (*PresignedPart) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{2}
}

func (x *PresignedPart) GetPartNumber() int32 {
	if x != nil {
		return x.PartNumber
	}
	return 0
}

func (x *PresignedPart) GetPresignedUrl() string {
	if x != nil {
		return x.PresignedUrl
	}
	return ""
}

type CompleteUploadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UploadId       string                 `protobuf:"bytes,2,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	Parts          []*UploadPart          `protobuf:"bytes,3,rep,name=parts,proto3" json:"parts,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CompleteUploadRequest) Reset() {
	*x = CompleteUploadRequest{}
	mi := &file_proto_media_v1_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteUploadRequest) ProtoMessage() {}

func (x *CompleteUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteUploadRequest.ProtoReflect.Descriptor instead.
func (*CompleteUploadRequest) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{3}
}

func (x *CompleteUploadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CompleteUploadRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *CompleteUploadRequest) GetParts() []*UploadPart {
	if x != nil {
		return x.Parts
	}
	return nil
}

func (x *CompleteUploadRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type UploadPart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartNumber    int32                  `protobuf:"varint,1,opt,name=part_number,json=partNumber,proto3" json:"part_number,omitempty"`
	ETag          string                 `protobuf:"bytes,2,opt,name=e_tag,json=eTag,proto3" json:"e_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPart) Reset() {
	*x = UploadPart{}
	mi := &file_proto_media_v1_media_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPart) ProtoMessage() {}

func (x *UploadPart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPart.ProtoReflect.Descriptor instead.
func (*UploadPart) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{4}
}

func (x *UploadPart) GetPartNumber() int32 {
	if x != nil {
		return x.PartNumber
	}
	return 0
}

func (x *UploadPart) GetETag() string {
	if x != nil {
		return x.ETag
	}
	return ""
}

type CompleteUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteUploadResponse) Reset() {
	*x = CompleteUploadResponse{}
	mi := &file_proto_media_v1_media_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteUploadResponse) ProtoMessage() {}

func (x *CompleteUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteUploadResponse.ProtoReflect.Descriptor instead.
func (*CompleteUploadResponse) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{5}
}

func (x *CompleteUploadResponse) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *CompleteUploadResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AbortUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UploadId      string                 `protobuf:"bytes,2,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortUploadRequest) Reset() {
	*x = AbortUploadRequest{}
	mi := &file_proto_media_v1_media_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortUploadRequest) ProtoMessage() {}

func (x *AbortUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortUploadRequest.ProtoReflect.Descriptor instead.
func (*AbortUploadRequest) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{6}
}

func (x *AbortUploadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AbortUploadRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

type AbortUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortUploadResponse) Reset() {
	*x = AbortUploadResponse{}
	mi := &file_proto_media_v1_media_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortUploadResponse) ProtoMessage() {}

func (x *AbortUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortUploadResponse.ProtoReflect.Descriptor instead.
func (*AbortUploadResponse) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{7}
}

func (x *AbortUploadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetUploadStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UploadId      string                 `protobuf:"bytes,2,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadStatusRequest) Reset() {
	*x = GetUploadStatusRequest{}
	mi := &file_proto_media_v1_media_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadStatusRequest) ProtoMessage() {}

func (x *GetUploadStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadStatusRequest.ProtoReflect.Descriptor instead.
func (*GetUploadStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{8}
}

func (x *GetUploadStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUploadStatusRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

type GetUploadStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UploadId       string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	TotalParts     int32                  `protobuf:"varint,3,opt,name=total_parts,json=totalParts,proto3" json:"total_parts,omitempty"`
	CompletedParts int32                  `protobuf:"varint,4,opt,name=completed_parts,json=completedParts,proto3" json:"completed_parts,omitempty"`
	MissingParts   []int32                `protobuf:"varint,5,rep,packed,name=missing_parts,json=missingParts,proto3" json:"missing_parts,omitempty"`
	ExpiresAt      int64                  `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // unix seconds
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUploadStatusResponse) Reset() {
	*x = GetUploadStatusResponse{}
	mi := &file_proto_media_v1_media_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadStatusResponse) ProtoMessage() {}

func (x *GetUploadStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadStatusResponse.ProtoReflect.Descriptor instead.
func (*GetUploadStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{9}
}

func (x *GetUploadStatusResponse) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *GetUploadStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetUploadStatusResponse) GetTotalParts() int32 {
	if x != nil {
		return x.TotalParts
	}
	return 0
}

func (x *GetUploadStatusResponse) GetCompletedParts() int32 {
	if x != nil {
		return x.CompletedParts
	}
	return 0
}

func (x *GetUploadStatusResponse) GetMissingParts() []int32 {
	if x != nil {
		return x.MissingParts
	}
	return nil
}

func (x *GetUploadStatusResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type GetMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MediaId       string                 `protobuf:"bytes,2,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaRequest) Reset() {
	*x = GetMediaRequest{}
	mi := &file_proto_media_v1_media_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaRequest) ProtoMessage() {}

func (x *GetMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaRequest.ProtoReflect.Descriptor instead.
func (*GetMediaRequest) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{10}
}

func (x *GetMediaRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetMediaRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

type GetMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *MediaInfo             `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaResponse) Reset() {
	*x = GetMediaResponse{}
	mi := &file_proto_media_v1_media_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaResponse) ProtoMessage() {}

func (x *GetMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaResponse.ProtoReflect.Descriptor instead.
func (*GetMediaResponse) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{11}
}

func (x *GetMediaResponse) GetMedia() *MediaInfo {
	if x != nil {
		return x.Media
	}
	return nil
}

type MediaInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	MediaType     string                 `protobuf:"bytes,5,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Size          int64                  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,8,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix seconds
	UpdatedAt     int64                  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Versions      []*MediaVersionInfo    `protobuf:"bytes,11,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaInfo) Reset() {
	*x = MediaInfo{}
	mi := &file_proto_media_v1_media_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaInfo) ProtoMessage() {}

func (x *MediaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaInfo.ProtoReflect.Descriptor instead.
func (*MediaInfo) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{12}
}

func (x *MediaInfo) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *MediaInfo) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *MediaInfo) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *MediaInfo) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *MediaInfo) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *MediaInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *MediaInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MediaInfo) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *MediaInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *MediaInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *MediaInfo) GetVersions() []*MediaVersionInfo {
	if x != nil {
		return x.Versions
	}
	return nil
}

type MediaVersionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VersionType   string                 `protobuf:"bytes,1,opt,name=version_type,json=versionType,proto3" json:"version_type,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,2,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Width         int32                  `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	DurationMs    int64                  `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaVersionInfo) Reset() {
	*x = MediaVersionInfo{}
	mi := &file_proto_media_v1_media_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaVersionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaVersionInfo) ProtoMessage() {}

func (x *MediaVersionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaVersionInfo.ProtoReflect.Descriptor instead.
func (*MediaVersionInfo) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{13}
}

func (x *MediaVersionInfo) GetVersionType() string {
	if x != nil {
		return x.VersionType
	}
	return ""
}

func (x *MediaVersionInfo) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *MediaVersionInfo) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *MediaVersionInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *MediaVersionInfo) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MediaVersionInfo) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MediaVersionInfo) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type ListMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	StatusFilter  string                 `protobuf:"bytes,4,opt,name=status_filter,json=statusFilter,proto3" json:"status_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMediaRequest) Reset() {
	*x = ListMediaRequest{}
	mi := &file_proto_media_v1_media_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMediaRequest) ProtoMessage() {}

func (x *ListMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMediaRequest.ProtoReflect.Descriptor instead.
func (*ListMediaRequest) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{14}
}

func (x *ListMediaRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ListMediaRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMediaRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListMediaRequest) GetStatusFilter() string {
	if x != nil {
		return x.StatusFilter
	}
	return ""
}

type ListMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MediaInfo           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMediaResponse) Reset() {
	*x = ListMediaResponse{}
	mi := &file_proto_media_v1_media_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMediaResponse) ProtoMessage() {}

func (x *ListMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMediaResponse.ProtoReflect.Descriptor instead.
func (*ListMediaResponse) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{15}
}

func (x *ListMediaResponse) GetItems() []*MediaInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListMediaResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type GetDownloadUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MediaId       string                 `protobuf:"bytes,2,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	VersionType   string                 `protobuf:"bytes,3,opt,name=version_type,json=versionType,proto3" json:"version_type,omitempty"` // "original", "thumbnail", "720p", etc.
	ExpirySeconds int32                  `protobuf:"varint,4,opt,name=expiry_seconds,json=expirySeconds,proto3" json:"expiry_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrlRequest) Reset() {
	*x = GetDownloadUrlRequest{}
	mi := &file_proto_media_v1_media_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrlRequest) ProtoMessage() {}

func (x *GetDownloadUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrlRequest.ProtoReflect.Descriptor instead.
func (*GetDownloadUrlRequest) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{16}
}

func (x *GetDownloadUrlRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetDownloadUrlRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *GetDownloadUrlRequest) GetVersionType() string {
	if x != nil {
		return x.VersionType
	}
	return ""
}

func (x *GetDownloadUrlRequest) GetExpirySeconds() int32 {
	if x != nil {
		return x.ExpirySeconds
	}
	return 0
}

type GetDownloadUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"` // NEVER log this field
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrlResponse) Reset() {
	*x = GetDownloadUrlResponse{}
	mi := &file_proto_media_v1_media_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrlResponse) ProtoMessage() {}

func (x *GetDownloadUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrlResponse.ProtoReflect.Descriptor instead.
func (*GetDownloadUrlResponse) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{17}
}

func (x *GetDownloadUrlResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetDownloadUrlResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *GetDownloadUrlResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type DeleteMediaRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MediaId        string                 `protobuf:"bytes,2,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteMediaRequest) Reset() {
	*x = DeleteMediaRequest{}
	mi := &file_proto_media_v1_media_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMediaRequest) ProtoMessage() {}

func (x *DeleteMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMediaRequest.ProtoReflect.Descriptor instead.
func (*DeleteMediaRequest) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteMediaRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteMediaRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *DeleteMediaRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type DeleteMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"` // always true — deletion is async
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMediaResponse) Reset() {
	*x = DeleteMediaResponse{}
	mi := &file_proto_media_v1_media_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMediaResponse) ProtoMessage() {}

func (x *DeleteMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMediaResponse.ProtoReflect.Descriptor instead.
func (*DeleteMediaResponse) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteMediaResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type GetQuotaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuotaRequest) Reset() {
	*x = GetQuotaRequest{}
	mi := &file_proto_media_v1_media_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuotaRequest) ProtoMessage() {}

func (x *GetQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuotaRequest.ProtoReflect.Descriptor instead.
func (*GetQuotaRequest) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{20}
}

func (x *GetQuotaRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetQuotaResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UsedBytes            int64                  `protobuf:"varint,1,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	QuotaBytes           int64                  `protobuf:"varint,2,opt,name=quota_bytes,json=quotaBytes,proto3" json:"quota_bytes,omitempty"`
	RemainingBytes       int64                  `protobuf:"varint,3,opt,name=remaining_bytes,json=remainingBytes,proto3" json:"remaining_bytes,omitempty"`
	ActiveUploads        int32                  `protobuf:"varint,4,opt,name=active_uploads,json=activeUploads,proto3" json:"active_uploads,omitempty"`
	MaxConcurrentUploads int32                  `protobuf:"varint,5,opt,name=max_concurrent_uploads,json=maxConcurrentUploads,proto3" json:"max_concurrent_uploads,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetQuotaResponse) Reset() {
	*x = GetQuotaResponse{}
	mi := &file_proto_media_v1_media_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuotaResponse) ProtoMessage() {}

func (x *GetQuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuotaResponse.ProtoReflect.Descriptor instead.
func (*GetQuotaResponse) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{21}
}

func (x *GetQuotaResponse) GetUsedBytes() int64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *GetQuotaResponse) GetQuotaBytes() int64 {
	if x != nil {
		return x.QuotaBytes
	}
	return 0
}

func (x *GetQuotaResponse) GetRemainingBytes() int64 {
	if x != nil {
		return x.RemainingBytes
	}
	return 0
}

func (x *GetQuotaResponse) GetActiveUploads() int32 {
	if x != nil {
		return x.ActiveUploads
	}
	return 0
}

func (x *GetQuotaResponse) GetMaxConcurrentUploads() int32 {
	if x != nil {
		return x.MaxConcurrentUploads
	}
	return 0
}

var File_proto_media_v1_media_proto protoreflect.FileDescriptor

const file_proto_media_v1_media_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/media/v1/media.proto\x12\bmedia.v1\"\xef\x01\n" +
	"\x1aCreateUploadSessionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x1a\n" +
	"\bchecksum\x18\x05 \x01(\tR\bchecksum\x12\x1f\n" +
	"\vdelivery_id\x18\x06 \x01(\tR\n" +
	"deliveryId\x12'\n" +
	"\x0fidempotency_key\x18\a \x01(\tR\x0eidempotencyKey\"\x96\x02\n" +
	"\x1bCreateUploadSessionResponse\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\x1b\n" +
	"\tupload_id\x18\x02 \x01(\tR\buploadId\x12 \n" +
	"\fs3_upload_id\x18\x03 \x01(\tR\n" +
	"s3UploadId\x12@\n" +
	"\x0fpresigned_parts\x18\x04 \x03(\v2\x17.media.v1.PresignedPartR\x0epresignedParts\x12\x1b\n" +
	"\tpart_size\x18\x05 \x01(\x03R\bpartSize\x12\x1f\n" +
	"\vtotal_parts\x18\x06 \x01(\x05R\n" +
	"totalParts\x12\x1d\n" +
	"\n" +
	"expires_at\x18\a \x01(\x03R\texpiresAt\"U\n" +
	"\rPresignedPart\x12\x1f\n" +
	"\vpart_number\x18\x01 \x01(\x05R\n" +
	"partNumber\x12#\n" +
	"\rpresigned_url\x18\x02 \x01(\tR\fpresignedUrl\"\xa2\x01\n" +
	"\x15CompleteUploadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tupload_id\x18\x02 \x01(\tR\buploadId\x12*\n" +
	"\x05parts\x18\x03 \x03(\v2\x14.media.v1.UploadPartR\x05parts\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\"B\n" +
	"\n" +
	"UploadPart\x12\x1f\n" +
	"\vpart_number\x18\x01 \x01(\x05R\n" +
	"partNumber\x12\x13\n" +
	"\x05e_tag\x18\x02 \x01(\tR\x04eTag\"K\n" +
	"\x16CompleteUploadResponse\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"J\n" +
	"\x12AbortUploadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tupload_id\x18\x02 \x01(\tR\buploadId\"/\n" +
	"\x13AbortUploadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"N\n" +
	"\x16GetUploadStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tupload_id\x18\x02 \x01(\tR\buploadId\"\xdc\x01\n" +
	"\x17GetUploadStatusResponse\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vtotal_parts\x18\x03 \x01(\x05R\n" +
	"totalParts\x12'\n" +
	"\x0fcompleted_parts\x18\x04 \x01(\x05R\x0ecompletedParts\x12#\n" +
	"\rmissing_parts\x18\x05 \x03(\x05R\fmissingParts\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\x03R\texpiresAt\"E\n" +
	"\x0fGetMediaRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bmedia_id\x18\x02 \x01(\tR\amediaId\"=\n" +
	"\x10GetMediaResponse\x12)\n" +
	"\x05media\x18\x01 \x01(\v2\x13.media.v1.MediaInfoR\x05media\"\xe1\x02\n" +
	"\tMediaInfo\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"media_type\x18\x05 \x01(\tR\tmediaType\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"object_key\x18\b \x01(\tR\tobjectKey\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\x126\n" +
	"\bversions\x18\v \x03(\v2\x1a.media.v1.MediaVersionInfoR\bversions\"\xda\x01\n" +
	"\x10MediaVersionInfo\x12!\n" +
	"\fversion_type\x18\x01 \x01(\tR\vversionType\x12\x1d\n" +
	"\n" +
	"object_key\x18\x02 \x01(\tR\tobjectKey\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x14\n" +
	"\x05width\x18\x05 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x06 \x01(\x05R\x06height\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x03R\n" +
	"durationMs\"\x80\x01\n" +
	"\x10ListMediaRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\x12#\n" +
	"\rstatus_filter\x18\x04 \x01(\tR\fstatusFilter\"_\n" +
	"\x11ListMediaResponse\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.media.v1.MediaInfoR\x05items\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"\x95\x01\n" +
	"\x15GetDownloadUrlRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bmedia_id\x18\x02 \x01(\tR\amediaId\x12!\n" +
	"\fversion_type\x18\x03 \x01(\tR\vversionType\x12%\n" +
	"\x0eexpiry_seconds\x18\x04 \x01(\x05R\rexpirySeconds\"l\n" +
	"\x16GetDownloadUrlResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"q\n" +
	"\x12DeleteMediaRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bmedia_id\x18\x02 \x01(\tR\amediaId\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\"1\n" +
	"\x13DeleteMediaResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"*\n" +
	"\x0fGetQuotaRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xd8\x01\n" +
	"\x10GetQuotaResponse\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x01 \x01(\x03R\tusedBytes\x12\x1f\n" +
	"\vquota_bytes\x18\x02 \x01(\x03R\n" +
	"quotaBytes\x12'\n" +
	"\x0fremaining_bytes\x18\x03 \x01(\x03R\x0eremainingBytes\x12%\n" +
	"\x0eactive_uploads\x18\x04 \x01(\x05R\ractiveUploads\x124\n" +
	"\x16max_concurrent_uploads\x18\x05 \x01(\x05R\x14maxConcurrentUploads2\xd8\x05\n" +
	"\fMediaService\x12b\n" +
	"\x13CreateUploadSession\x12$.media.v1.CreateUploadSessionRequest\x1a%.media.v1.CreateUploadSessionResponse\x12V\n" +
	"\x0fGetUploadStatus\x12 .media.v1.GetUploadStatusRequest\x1a!.media.v1.GetUploadStatusResponse\x12S\n" +
	"\x0eCompleteUpload\x12\x1f.media.v1.CompleteUploadRequest\x1a .media.v1.CompleteUploadResponse\x12J\n" +
	"\vAbortUpload\x12\x1c.media.v1.AbortUploadRequest\x1a\x1d.media.v1.AbortUploadResponse\x12A\n" +
	"\bGetMedia\x12\x19.media.v1.GetMediaRequest\x1a\x1a.media.v1.GetMediaResponse\x12D\n" +
	"\tListMedia\x12\x1a.media.v1.ListMediaRequest\x1a\x1b.media.v1.ListMediaResponse\x12S\n" +
	"\x0eGetDownloadUrl\x12\x1f.media.v1.GetDownloadUrlRequest\x1a .media.v1.GetDownloadUrlResponse\x12J\n" +
	"\vDeleteMedia\x12\x1c.media.v1.DeleteMediaRequest\x1a\x1d.media.v1.DeleteMediaResponse\x12A\n" +
	"\bGetQuota\x12\x19.media.v1.GetQuotaRequest\x1a\x1a.media.v1.GetQuotaResponseBeZcgithub.com/Omar-Sa6ry/Realtime-Delivery-microservices/services/media-service/proto/media/v1;mediav1b\x06proto3"

var (
	file_proto_media_v1_media_proto_rawDescOnce sync.Once
	file_proto_media_v1_media_proto_rawDescData []byte
)

func file_proto_media_v1_media_proto_rawDescGZIP() []byte {
	file_proto_media_v1_media_proto_rawDescOnce.Do(func() {
		file_proto_media_v1_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_media_v1_media_proto_rawDesc), len(file_proto_media_v1_media_proto_rawDesc)))
	})
	return file_proto_media_v1_media_proto_rawDescData
}

var file_proto_media_v1_media_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_media_v1_media_proto_goTypes = []any{
	(*CreateUploadSessionRequest)(nil),  // 0: media.v1.CreateUploadSessionRequest
	(*CreateUploadSessionResponse)(nil), // 1: media.v1.CreateUploadSessionResponse
	(*PresignedPart)(nil),               // 2: media.v1.PresignedPart
	(*CompleteUploadRequest)(nil),       // 3: media.v1.CompleteUploadRequest
	(*UploadPart)(nil),                  // 4: media.v1.UploadPart
	(*CompleteUploadResponse)(nil),      // 5: media.v1.CompleteUploadResponse
	(*AbortUploadRequest)(nil),          // 6: media.v1.AbortUploadRequest
	(*AbortUploadResponse)(nil),         // 7: media.v1.AbortUploadResponse
	(*GetUploadStatusRequest)(nil),      // 8: media.v1.GetUploadStatusRequest
	(*GetUploadStatusResponse)(nil),     // 9: media.v1.GetUploadStatusResponse
	(*GetMediaRequest)(nil),             // 10: media.v1.GetMediaRequest
	(*GetMediaResponse)(nil),            // 11: media.v1.GetMediaResponse
	(*MediaInfo)(nil),                   // 12: media.v1.MediaInfo
	(*MediaVersionInfo)(nil),            // 13: media.v1.MediaVersionInfo
	(*ListMediaRequest)(nil),            // 14: media.v1.ListMediaRequest
	(*ListMediaResponse)(nil),           // 15: media.v1.ListMediaResponse
	(*GetDownloadUrlRequest)(nil),       // 16: media.v1.GetDownloadUrlRequest
	(*GetDownloadUrlResponse)(nil),      // 17: media.v1.GetDownloadUrlResponse
	(*DeleteMediaRequest)(nil),          // 18: media.v1.DeleteMediaRequest
	(*DeleteMediaResponse)(nil),         // 19: media.v1.DeleteMediaResponse
	(*GetQuotaRequest)(nil),             // 20: media.v1.GetQuotaRequest
	(*GetQuotaResponse)(nil),            // 21: media.v1.GetQuotaResponse
}
var file_proto_media_v1_media_proto_depIdxs = []int32{
	2,  // 0: media.v1.CreateUploadSessionResponse.presigned_parts:type_name -> media.v1.PresignedPart
	4,  // 1: media.v1.CompleteUploadRequest.parts:type_name -> media.v1.UploadPart
	12, // 2: media.v1.GetMediaResponse.media:type_name -> media.v1.MediaInfo
	13, // 3: media.v1.MediaInfo.versions:type_name -> media.v1.MediaVersionInfo
	12, // 4: media.v1.ListMediaResponse.items:type_name -> media.v1.MediaInfo
	0,  // 5: media.v1.MediaService.CreateUploadSession:input_type -> media.v1.CreateUploadSessionRequest
	8,  // 6: media.v1.MediaService.GetUploadStatus:input_type -> media.v1.GetUploadStatusRequest
	3,  // 7: media.v1.MediaService.CompleteUpload:input_type -> media.v1.CompleteUploadRequest
	6,  // 8: media.v1.MediaService.AbortUpload:input_type -> media.v1.AbortUploadRequest
	10, // 9: media.v1.MediaService.GetMedia:input_type -> media.v1.GetMediaRequest
	14, // 10: media.v1.MediaService.ListMedia:input_type -> media.v1.ListMediaRequest
	16, // 11: media.v1.MediaService.GetDownloadUrl:input_type -> media.v1.GetDownloadUrlRequest
	18, // 12: media.v1.MediaService.DeleteMedia:input_type -> media.v1.DeleteMediaRequest
	20, // 13: media.v1.MediaService.GetQuota:input_type -> media.v1.GetQuotaRequest
	1,  // 14: media.v1.MediaService.CreateUploadSession:output_type -> media.v1.CreateUploadSessionResponse
	9,  // 15: media.v1.MediaService.GetUploadStatus:output_type -> media.v1.GetUploadStatusResponse
	5,  // 16: media.v1.MediaService.CompleteUpload:output_type -> media.v1.CompleteUploadResponse
	7,  // 17: media.v1.MediaService.AbortUpload:output_type -> media.v1.AbortUploadResponse
	11, // 18: media.v1.MediaService.GetMedia:output_type -> media.v1.GetMediaResponse
	15, // 19: media.v1.MediaService.ListMedia:output_type -> media.v1.ListMediaResponse
	17, // 20: media.v1.MediaService.GetDownloadUrl:output_type -> media.v1.GetDownloadUrlResponse
	19, // 21: media.v1.MediaService.DeleteMedia:output_type -> media.v1.DeleteMediaResponse
	21, // 22: media.v1.MediaService.GetQuota:output_type -> media.v1.GetQuotaResponse
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_media_v1_media_proto_init() }
func file_proto_media_v1_media_proto_init() {
	if File_proto_media_v1_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_media_v1_media_proto_rawDesc), len(file_proto_media_v1_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_media_v1_media_proto_goTypes,
		DependencyIndexes: file_proto_media_v1_media_proto_depIdxs,
		MessageInfos:      file_proto_media_v1_media_proto_msgTypes,
	}.Build()
	File_proto_media_v1_media_proto = out.File
	file_proto_media_v1_media_proto_goTypes = nil
	file_proto_media_v1_media_proto_depIdxs = nil
}
