// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: driver.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VehicleType int32

const (
	VehicleType_VEHICLE_TYPE_UNKNOWN VehicleType = 0
	VehicleType_CAR                  VehicleType = 1
	VehicleType_MOTORCYCLE           VehicleType = 2
	VehicleType_TRUCK                VehicleType = 3
	VehicleType_BICYCLE              VehicleType = 4
	VehicleType_VAN                  VehicleType = 5
)

// Enum value maps for VehicleType.
var (
	VehicleType_name = map[int32]string{
		0: "VEHICLE_TYPE_UNKNOWN",
		1: "CAR",
		2: "MOTORCYCLE",
		3: "TRUCK",
		4: "BICYCLE",
		5: "VAN",
	}
	VehicleType_value = map[string]int32{
		"VEHICLE_TYPE_UNKNOWN": 0,
		"CAR":                  1,
		"MOTORCYCLE":           2,
		"TRUCK":                3,
		"BICYCLE":              4,
		"VAN":                  5,
	}
)

func (x VehicleType) Enum() *VehicleType {
	p := new(VehicleType)
	*p = x
	return p
}

func (x VehicleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VehicleType) Descriptor() protoreflect.EnumDescriptor {
	return file_driver_proto_enumTypes[0].Descriptor()
}

func (VehicleType) Type() protoreflect.EnumType {
	return &file_driver_proto_enumTypes[0]
}

func (x VehicleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VehicleType.Descriptor instead.
func (VehicleType) EnumDescriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{0}
}

type ValidateIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IdType        string                 `protobuf:"bytes,2,opt,name=idType,proto3" json:"idType,omitempty"`   // "driver", "delivery", "user"
	Context       string                 `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"` // optional context for validation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateIDRequest) Reset() {
	*x = ValidateIDRequest{}
	mi := &file_driver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateIDRequest) ProtoMessage() {}

func (x *ValidateIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateIDRequest.ProtoReflect.Descriptor instead.
func (*ValidateIDRequest) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ValidateIDRequest) GetIdType() string {
	if x != nil {
		return x.IdType
	}
	return ""
}

func (x *ValidateIDRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

type ValidateIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driverId,proto3" json:"driverId,omitempty"` // if validating a driver ID
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`     // current status if found
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateIDResponse) Reset() {
	*x = ValidateIDResponse{}
	mi := &file_driver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateIDResponse) ProtoMessage() {}

func (x *ValidateIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateIDResponse.ProtoReflect.Descriptor instead.
func (*ValidateIDResponse) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateIDResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateIDResponse) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *ValidateIDResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ValidateIDResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FindAvailableDriversRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	RadiusKm      float64                `protobuf:"fixed64,3,opt,name=radiusKm,proto3" json:"radiusKm,omitempty"`
	VehicleType   VehicleType            `protobuf:"varint,4,opt,name=vehicleType,proto3,enum=driver.VehicleType" json:"vehicleType,omitempty"`
	DeliveryId    string                 `protobuf:"bytes,5,opt,name=deliveryId,proto3" json:"deliveryId,omitempty"`
	CorrelationId string                 `protobuf:"bytes,6,opt,name=correlationId,proto3" json:"correlationId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAvailableDriversRequest) Reset() {
	*x = FindAvailableDriversRequest{}
	mi := &file_driver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAvailableDriversRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAvailableDriversRequest) ProtoMessage() {}

func (x *FindAvailableDriversRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAvailableDriversRequest.ProtoReflect.Descriptor instead.
func (*FindAvailableDriversRequest) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{2}
}

func (x *FindAvailableDriversRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *FindAvailableDriversRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *FindAvailableDriversRequest) GetRadiusKm() float64 {
	if x != nil {
		return x.RadiusKm
	}
	return 0
}

func (x *FindAvailableDriversRequest) GetVehicleType() VehicleType {
	if x != nil {
		return x.VehicleType
	}
	return VehicleType_VEHICLE_TYPE_UNKNOWN
}

func (x *FindAvailableDriversRequest) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *FindAvailableDriversRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type DriverCandidate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DriverId       string                 `protobuf:"bytes,1,opt,name=driverId,proto3" json:"driverId,omitempty"`
	DistanceMeters float64                `protobuf:"fixed64,2,opt,name=distanceMeters,proto3" json:"distanceMeters,omitempty"`
	VehicleType    VehicleType            `protobuf:"varint,3,opt,name=vehicleType,proto3,enum=driver.VehicleType" json:"vehicleType,omitempty"`
	Latitude       float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude      float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DriverCandidate) Reset() {
	*x = DriverCandidate{}
	mi := &file_driver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverCandidate) ProtoMessage() {}

func (x *DriverCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverCandidate.ProtoReflect.Descriptor instead.
func (*DriverCandidate) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{3}
}

func (x *DriverCandidate) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *DriverCandidate) GetDistanceMeters() float64 {
	if x != nil {
		return x.DistanceMeters
	}
	return 0
}

func (x *DriverCandidate) GetVehicleType() VehicleType {
	if x != nil {
		return x.VehicleType
	}
	return VehicleType_VEHICLE_TYPE_UNKNOWN
}

func (x *DriverCandidate) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *DriverCandidate) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type FindAvailableDriversResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candidates    []*DriverCandidate     `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAvailableDriversResponse) Reset() {
	*x = FindAvailableDriversResponse{}
	mi := &file_driver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAvailableDriversResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAvailableDriversResponse) ProtoMessage() {}

func (x *FindAvailableDriversResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAvailableDriversResponse.ProtoReflect.Descriptor instead.
func (*FindAvailableDriversResponse) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{4}
}

func (x *FindAvailableDriversResponse) GetCandidates() []*DriverCandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type ReserveDriverRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DriverId       string                 `protobuf:"bytes,1,opt,name=driverId,proto3" json:"driverId,omitempty"`
	DeliveryId     string                 `protobuf:"bytes,2,opt,name=deliveryId,proto3" json:"deliveryId,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotencyKey,proto3" json:"idempotencyKey,omitempty"`
	CorrelationId  string                 `protobuf:"bytes,4,opt,name=correlationId,proto3" json:"correlationId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReserveDriverRequest) Reset() {
	*x = ReserveDriverRequest{}
	mi := &file_driver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveDriverRequest) ProtoMessage() {}

func (x *ReserveDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveDriverRequest.ProtoReflect.Descriptor instead.
func (*ReserveDriverRequest) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{5}
}

func (x *ReserveDriverRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *ReserveDriverRequest) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *ReserveDriverRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ReserveDriverRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type ReserveDriverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reserved      bool                   `protobuf:"varint,1,opt,name=reserved,proto3" json:"reserved,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driverId,proto3" json:"driverId,omitempty"`
	DeliveryId    string                 `protobuf:"bytes,3,opt,name=deliveryId,proto3" json:"deliveryId,omitempty"`
	AssignmentId  string                 `protobuf:"bytes,4,opt,name=assignmentId,proto3" json:"assignmentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveDriverResponse) Reset() {
	*x = ReserveDriverResponse{}
	mi := &file_driver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveDriverResponse) ProtoMessage() {}

func (x *ReserveDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveDriverResponse.ProtoReflect.Descriptor instead.
func (*ReserveDriverResponse) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{6}
}

func (x *ReserveDriverResponse) GetReserved() bool {
	if x != nil {
		return x.Reserved
	}
	return false
}

func (x *ReserveDriverResponse) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *ReserveDriverResponse) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *ReserveDriverResponse) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

type ReleaseDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driverId,proto3" json:"driverId,omitempty"`
	DeliveryId    string                 `protobuf:"bytes,2,opt,name=deliveryId,proto3" json:"deliveryId,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	CorrelationId string                 `protobuf:"bytes,4,opt,name=correlationId,proto3" json:"correlationId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseDriverRequest) Reset() {
	*x = ReleaseDriverRequest{}
	mi := &file_driver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseDriverRequest) ProtoMessage() {}

func (x *ReleaseDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseDriverRequest.ProtoReflect.Descriptor instead.
func (*ReleaseDriverRequest) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{7}
}

func (x *ReleaseDriverRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *ReleaseDriverRequest) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *ReleaseDriverRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ReleaseDriverRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type ReleaseDriverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Released      bool                   `protobuf:"varint,1,opt,name=released,proto3" json:"released,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driverId,proto3" json:"driverId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseDriverResponse) Reset() {
	*x = ReleaseDriverResponse{}
	mi := &file_driver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseDriverResponse) ProtoMessage() {}

func (x *ReleaseDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseDriverResponse.ProtoReflect.Descriptor instead.
func (*ReleaseDriverResponse) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{8}
}

func (x *ReleaseDriverResponse) GetReleased() bool {
	if x != nil {
		return x.Released
	}
	return false
}

func (x *ReleaseDriverResponse) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type AssignDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driverId,proto3" json:"driverId,omitempty"`
	DeliveryId    string                 `protobuf:"bytes,2,opt,name=deliveryId,proto3" json:"deliveryId,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=correlationId,proto3" json:"correlationId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignDriverRequest) Reset() {
	*x = AssignDriverRequest{}
	mi := &file_driver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignDriverRequest) ProtoMessage() {}

func (x *AssignDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignDriverRequest.ProtoReflect.Descriptor instead.
func (*AssignDriverRequest) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{9}
}

func (x *AssignDriverRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *AssignDriverRequest) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *AssignDriverRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type AssignDriverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assigned      bool                   `protobuf:"varint,1,opt,name=assigned,proto3" json:"assigned,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driverId,proto3" json:"driverId,omitempty"`
	DeliveryId    string                 `protobuf:"bytes,3,opt,name=deliveryId,proto3" json:"deliveryId,omitempty"`
	AssignmentId  string                 `protobuf:"bytes,4,opt,name=assignmentId,proto3" json:"assignmentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignDriverResponse) Reset() {
	*x = AssignDriverResponse{}
	mi := &file_driver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignDriverResponse) ProtoMessage() {}

func (x *AssignDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignDriverResponse.ProtoReflect.Descriptor instead.
func (*AssignDriverResponse) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{10}
}

func (x *AssignDriverResponse) GetAssigned() bool {
	if x != nil {
		return x.Assigned
	}
	return false
}

func (x *AssignDriverResponse) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *AssignDriverResponse) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *AssignDriverResponse) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

type GetDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driverId,proto3" json:"driverId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverRequest) Reset() {
	*x = GetDriverRequest{}
	mi := &file_driver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverRequest) ProtoMessage() {}

func (x *GetDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverRequest.ProtoReflect.Descriptor instead.
func (*GetDriverRequest) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{11}
}

func (x *GetDriverRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type GetDriverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driverId,proto3" json:"driverId,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	VehicleType   VehicleType            `protobuf:"varint,5,opt,name=vehicleType,proto3,enum=driver.VehicleType" json:"vehicleType,omitempty"`
	IsBlocked     bool                   `protobuf:"varint,6,opt,name=is_blocked,json=isBlocked,proto3" json:"is_blocked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverResponse) Reset() {
	*x = GetDriverResponse{}
	mi := &file_driver_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverResponse) ProtoMessage() {}

func (x *GetDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverResponse.ProtoReflect.Descriptor instead.
func (*GetDriverResponse) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{12}
}

func (x *GetDriverResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetDriverResponse) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *GetDriverResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetDriverResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetDriverResponse) GetVehicleType() VehicleType {
	if x != nil {
		return x.VehicleType
	}
	return VehicleType_VEHICLE_TYPE_UNKNOWN
}

func (x *GetDriverResponse) GetIsBlocked() bool {
	if x != nil {
		return x.IsBlocked
	}
	return false
}

type GetDriverStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driverId,proto3" json:"driverId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverStatusRequest) Reset() {
	*x = GetDriverStatusRequest{}
	mi := &file_driver_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverStatusRequest) ProtoMessage() {}

func (x *GetDriverStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverStatusRequest.ProtoReflect.Descriptor instead.
func (*GetDriverStatusRequest) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{13}
}

func (x *GetDriverStatusRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type GetDriverStatusResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DriverId            string                 `protobuf:"bytes,1,opt,name=driverId,proto3" json:"driverId,omitempty"`
	Status              string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	HasActiveAssignment bool                   `protobuf:"varint,3,opt,name=hasActiveAssignment,proto3" json:"hasActiveAssignment,omitempty"`
	ActiveDeliveryId    string                 `protobuf:"bytes,4,opt,name=activeDeliveryId,proto3" json:"activeDeliveryId,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetDriverStatusResponse) Reset() {
	*x = GetDriverStatusResponse{}
	mi := &file_driver_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverStatusResponse) ProtoMessage() {}

func (x *GetDriverStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverStatusResponse.ProtoReflect.Descriptor instead.
func (*GetDriverStatusResponse) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{14}
}

func (x *GetDriverStatusResponse) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *GetDriverStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetDriverStatusResponse) GetHasActiveAssignment() bool {
	if x != nil {
		return x.HasActiveAssignment
	}
	return false
}

func (x *GetDriverStatusResponse) GetActiveDeliveryId() string {
	if x != nil {
		return x.ActiveDeliveryId
	}
	return ""
}

var File_driver_proto protoreflect.FileDescriptor

const file_driver_proto_rawDesc = "" +
	"\n" +
	"\fdriver.proto\x12\x06driver\"U\n" +
	"\x11ValidateIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06idType\x18\x02 \x01(\tR\x06idType\x12\x18\n" +
	"\acontext\x18\x03 \x01(\tR\acontext\"x\n" +
	"\x12ValidateIDResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x1a\n" +
	"\bdriverId\x18\x02 \x01(\tR\bdriverId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xf0\x01\n" +
	"\x1bFindAvailableDriversRequest\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\bradiusKm\x18\x03 \x01(\x01R\bradiusKm\x125\n" +
	"\vvehicleType\x18\x04 \x01(\x0e2\x13.driver.VehicleTypeR\vvehicleType\x12\x1e\n" +
	"\n" +
	"deliveryId\x18\x05 \x01(\tR\n" +
	"deliveryId\x12$\n" +
	"\rcorrelationId\x18\x06 \x01(\tR\rcorrelationId\"\xc6\x01\n" +
	"\x0fDriverCandidate\x12\x1a\n" +
	"\bdriverId\x18\x01 \x01(\tR\bdriverId\x12&\n" +
	"\x0edistanceMeters\x18\x02 \x01(\x01R\x0edistanceMeters\x125\n" +
	"\vvehicleType\x18\x03 \x01(\x0e2\x13.driver.VehicleTypeR\vvehicleType\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\"W\n" +
	"\x1cFindAvailableDriversResponse\x127\n" +
	"\n" +
	"candidates\x18\x01 \x03(\v2\x17.driver.DriverCandidateR\n" +
	"candidates\"\xa0\x01\n" +
	"\x14ReserveDriverRequest\x12\x1a\n" +
	"\bdriverId\x18\x01 \x01(\tR\bdriverId\x12\x1e\n" +
	"\n" +
	"deliveryId\x18\x02 \x01(\tR\n" +
	"deliveryId\x12&\n" +
	"\x0eidempotencyKey\x18\x03 \x01(\tR\x0eidempotencyKey\x12$\n" +
	"\rcorrelationId\x18\x04 \x01(\tR\rcorrelationId\"\x93\x01\n" +
	"\x15ReserveDriverResponse\x12\x1a\n" +
	"\breserved\x18\x01 \x01(\bR\breserved\x12\x1a\n" +
	"\bdriverId\x18\x02 \x01(\tR\bdriverId\x12\x1e\n" +
	"\n" +
	"deliveryId\x18\x03 \x01(\tR\n" +
	"deliveryId\x12\"\n" +
	"\fassignmentId\x18\x04 \x01(\tR\fassignmentId\"\x90\x01\n" +
	"\x14ReleaseDriverRequest\x12\x1a\n" +
	"\bdriverId\x18\x01 \x01(\tR\bdriverId\x12\x1e\n" +
	"\n" +
	"deliveryId\x18\x02 \x01(\tR\n" +
	"deliveryId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12$\n" +
	"\rcorrelationId\x18\x04 \x01(\tR\rcorrelationId\"O\n" +
	"\x15ReleaseDriverResponse\x12\x1a\n" +
	"\breleased\x18\x01 \x01(\bR\breleased\x12\x1a\n" +
	"\bdriverId\x18\x02 \x01(\tR\bdriverId\"w\n" +
	"\x13AssignDriverRequest\x12\x1a\n" +
	"\bdriverId\x18\x01 \x01(\tR\bdriverId\x12\x1e\n" +
	"\n" +
	"deliveryId\x18\x02 \x01(\tR\n" +
	"deliveryId\x12$\n" +
	"\rcorrelationId\x18\x03 \x01(\tR\rcorrelationId\"\x92\x01\n" +
	"\x14AssignDriverResponse\x12\x1a\n" +
	"\bassigned\x18\x01 \x01(\bR\bassigned\x12\x1a\n" +
	"\bdriverId\x18\x02 \x01(\tR\bdriverId\x12\x1e\n" +
	"\n" +
	"deliveryId\x18\x03 \x01(\tR\n" +
	"deliveryId\x12\"\n" +
	"\fassignmentId\x18\x04 \x01(\tR\fassignmentId\".\n" +
	"\x10GetDriverRequest\x12\x1a\n" +
	"\bdriverId\x18\x01 \x01(\tR\bdriverId\"\xcb\x01\n" +
	"\x11GetDriverResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x1a\n" +
	"\bdriverId\x18\x02 \x01(\tR\bdriverId\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x125\n" +
	"\vvehicleType\x18\x05 \x01(\x0e2\x13.driver.VehicleTypeR\vvehicleType\x12\x1d\n" +
	"\n" +
	"is_blocked\x18\x06 \x01(\bR\tisBlocked\"4\n" +
	"\x16GetDriverStatusRequest\x12\x1a\n" +
	"\bdriverId\x18\x01 \x01(\tR\bdriverId\"\xab\x01\n" +
	"\x17GetDriverStatusResponse\x12\x1a\n" +
	"\bdriverId\x18\x01 \x01(\tR\bdriverId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x120\n" +
	"\x13hasActiveAssignment\x18\x03 \x01(\bR\x13hasActiveAssignment\x12*\n" +
	"\x10activeDeliveryId\x18\x04 \x01(\tR\x10activeDeliveryId*a\n" +
	"\vVehicleType\x12\x18\n" +
	"\x14VEHICLE_TYPE_UNKNOWN\x10\x00\x12\a\n" +
	"\x03CAR\x10\x01\x12\x0e\n" +
	"\n" +
	"MOTORCYCLE\x10\x02\x12\t\n" +
	"\x05TRUCK\x10\x03\x12\v\n" +
	"\aBICYCLE\x10\x04\x12\a\n" +
	"\x03VAN\x10\x052\xb4\x04\n" +
	"\rDriverService\x12a\n" +
	"\x14FindAvailableDrivers\x12#.driver.FindAvailableDriversRequest\x1a$.driver.FindAvailableDriversResponse\x12L\n" +
	"\rReserveDriver\x12\x1c.driver.ReserveDriverRequest\x1a\x1d.driver.ReserveDriverResponse\x12L\n" +
	"\rReleaseDriver\x12\x1c.driver.ReleaseDriverRequest\x1a\x1d.driver.ReleaseDriverResponse\x12@\n" +
	"\tGetDriver\x12\x18.driver.GetDriverRequest\x1a\x19.driver.GetDriverResponse\x12R\n" +
	"\x0fGetDriverStatus\x12\x1e.driver.GetDriverStatusRequest\x1a\x1f.driver.GetDriverStatusResponse\x12I\n" +
	"\fAssignDriver\x12\x1b.driver.AssignDriverRequest\x1a\x1c.driver.AssignDriverResponse\x12C\n" +
	"\n" +
	"ValidateID\x12\x19.driver.ValidateIDRequest\x1a\x1a.driver.ValidateIDResponseBlZjgithub.com/Omar-Sa6ry/Realtime-Delivery-microservices/services/driver-service/internal/adapters/grpc/protob\x06proto3"

var (
	file_driver_proto_rawDescOnce sync.Once
	file_driver_proto_rawDescData []byte
)

func file_driver_proto_rawDescGZIP() []byte {
	file_driver_proto_rawDescOnce.Do(func() {
		file_driver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_driver_proto_rawDesc), len(file_driver_proto_rawDesc)))
	})
	return file_driver_proto_rawDescData
}

var file_driver_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_driver_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_driver_proto_goTypes = []any{
	(VehicleType)(0),                     // 0: driver.VehicleType
	(*ValidateIDRequest)(nil),            // 1: driver.ValidateIDRequest
	(*ValidateIDResponse)(nil),           // 2: driver.ValidateIDResponse
	(*FindAvailableDriversRequest)(nil),  // 3: driver.FindAvailableDriversRequest
	(*DriverCandidate)(nil),              // 4: driver.DriverCandidate
	(*FindAvailableDriversResponse)(nil), // 5: driver.FindAvailableDriversResponse
	(*ReserveDriverRequest)(nil),         // 6: driver.ReserveDriverRequest
	(*ReserveDriverResponse)(nil),        // 7: driver.ReserveDriverResponse
	(*ReleaseDriverRequest)(nil),         // 8: driver.ReleaseDriverRequest
	(*ReleaseDriverResponse)(nil),        // 9: driver.ReleaseDriverResponse
	(*AssignDriverRequest)(nil),          // 10: driver.AssignDriverRequest
	(*AssignDriverResponse)(nil),         // 11: driver.AssignDriverResponse
	(*GetDriverRequest)(nil),             // 12: driver.GetDriverRequest
	(*GetDriverResponse)(nil),            // 13: driver.GetDriverResponse
	(*GetDriverStatusRequest)(nil),       // 14: driver.GetDriverStatusRequest
	(*GetDriverStatusResponse)(nil),      // 15: driver.GetDriverStatusResponse
}
var file_driver_proto_depIdxs = []int32{
	0,  // 0: driver.FindAvailableDriversRequest.vehicleType:type_name -> driver.VehicleType
	0,  // 1: driver.DriverCandidate.vehicleType:type_name -> driver.VehicleType
	4,  // 2: driver.FindAvailableDriversResponse.candidates:type_name -> driver.DriverCandidate
	0,  // 3: driver.GetDriverResponse.vehicleType:type_name -> driver.VehicleType
	3,  // 4: driver.DriverService.FindAvailableDrivers:input_type -> driver.FindAvailableDriversRequest
	6,  // 5: driver.DriverService.ReserveDriver:input_type -> driver.ReserveDriverRequest
	8,  // 6: driver.DriverService.ReleaseDriver:input_type -> driver.ReleaseDriverRequest
	12, // 7: driver.DriverService.GetDriver:input_type -> driver.GetDriverRequest
	14, // 8: driver.DriverService.GetDriverStatus:input_type -> driver.GetDriverStatusRequest
	10, // 9: driver.DriverService.AssignDriver:input_type -> driver.AssignDriverRequest
	1,  // 10: driver.DriverService.ValidateID:input_type -> driver.ValidateIDRequest
	5,  // 11: driver.DriverService.FindAvailableDrivers:output_type -> driver.FindAvailableDriversResponse
	7,  // 12: driver.DriverService.ReserveDriver:output_type -> driver.ReserveDriverResponse
	9,  // 13: driver.DriverService.ReleaseDriver:output_type -> driver.ReleaseDriverResponse
	13, // 14: driver.DriverService.GetDriver:output_type -> driver.GetDriverResponse
	15, // 15: driver.DriverService.GetDriverStatus:output_type -> driver.GetDriverStatusResponse
	11, // 16: driver.DriverService.AssignDriver:output_type -> driver.AssignDriverResponse
	2,  // 17: driver.DriverService.ValidateID:output_type -> driver.ValidateIDResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_driver_proto_init() }
func file_driver_proto_init() {
	if File_driver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_driver_proto_rawDesc), len(file_driver_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_driver_proto_goTypes,
		DependencyIndexes: file_driver_proto_depIdxs,
		EnumInfos:         file_driver_proto_enumTypes,
		MessageInfos:      file_driver_proto_msgTypes,
	}.Build()
	File_driver_proto = out.File
	file_driver_proto_goTypes = nil
	file_driver_proto_depIdxs = nil
}
