// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: driver.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DriverService_FindAvailableDrivers_FullMethodName = "/driver.DriverService/FindAvailableDrivers"
	DriverService_ReserveDriver_FullMethodName        = "/driver.DriverService/ReserveDriver"
	DriverService_ReleaseDriver_FullMethodName        = "/driver.DriverService/ReleaseDriver"
	DriverService_GetDriver_FullMethodName            = "/driver.DriverService/GetDriver"
	DriverService_GetDriverStatus_FullMethodName      = "/driver.DriverService/GetDriverStatus"
	DriverService_AssignDriver_FullMethodName         = "/driver.DriverService/AssignDriver"
	DriverService_ValidateID_FullMethodName           = "/driver.DriverService/ValidateID"
)

// DriverServiceClient is the client API for DriverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DriverServiceClient interface {
	FindAvailableDrivers(ctx context.Context, in *FindAvailableDriversRequest, opts ...grpc.CallOption) (*FindAvailableDriversResponse, error)
	ReserveDriver(ctx context.Context, in *ReserveDriverRequest, opts ...grpc.CallOption) (*ReserveDriverResponse, error)
	ReleaseDriver(ctx context.Context, in *ReleaseDriverRequest, opts ...grpc.CallOption) (*ReleaseDriverResponse, error)
	GetDriver(ctx context.Context, in *GetDriverRequest, opts ...grpc.CallOption) (*GetDriverResponse, error)
	GetDriverStatus(ctx context.Context, in *GetDriverStatusRequest, opts ...grpc.CallOption) (*GetDriverStatusResponse, error)
	AssignDriver(ctx context.Context, in *AssignDriverRequest, opts ...grpc.CallOption) (*AssignDriverResponse, error)
	ValidateID(ctx context.Context, in *ValidateIDRequest, opts ...grpc.CallOption) (*ValidateIDResponse, error)
}

type driverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDriverServiceClient(cc grpc.ClientConnInterface) DriverServiceClient {
	return &driverServiceClient{cc}
}

func (c *driverServiceClient) FindAvailableDrivers(ctx context.Context, in *FindAvailableDriversRequest, opts ...grpc.CallOption) (*FindAvailableDriversResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindAvailableDriversResponse)
	err := c.cc.Invoke(ctx, DriverService_FindAvailableDrivers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) ReserveDriver(ctx context.Context, in *ReserveDriverRequest, opts ...grpc.CallOption) (*ReserveDriverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveDriverResponse)
	err := c.cc.Invoke(ctx, DriverService_ReserveDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) ReleaseDriver(ctx context.Context, in *ReleaseDriverRequest, opts ...grpc.CallOption) (*ReleaseDriverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseDriverResponse)
	err := c.cc.Invoke(ctx, DriverService_ReleaseDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) GetDriver(ctx context.Context, in *GetDriverRequest, opts ...grpc.CallOption) (*GetDriverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDriverResponse)
	err := c.cc.Invoke(ctx, DriverService_GetDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) GetDriverStatus(ctx context.Context, in *GetDriverStatusRequest, opts ...grpc.CallOption) (*GetDriverStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDriverStatusResponse)
	err := c.cc.Invoke(ctx, DriverService_GetDriverStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) AssignDriver(ctx context.Context, in *AssignDriverRequest, opts ...grpc.CallOption) (*AssignDriverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignDriverResponse)
	err := c.cc.Invoke(ctx, DriverService_AssignDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) ValidateID(ctx context.Context, in *ValidateIDRequest, opts ...grpc.CallOption) (*ValidateIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateIDResponse)
	err := c.cc.Invoke(ctx, DriverService_ValidateID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DriverServiceServer is the server API for DriverService service.
// All implementations must embed UnimplementedDriverServiceServer
// for forward compatibility.
type DriverServiceServer interface {
	FindAvailableDrivers(context.Context, *FindAvailableDriversRequest) (*FindAvailableDriversResponse, error)
	ReserveDriver(context.Context, *ReserveDriverRequest) (*ReserveDriverResponse, error)
	ReleaseDriver(context.Context, *ReleaseDriverRequest) (*ReleaseDriverResponse, error)
	GetDriver(context.Context, *GetDriverRequest) (*GetDriverResponse, error)
	GetDriverStatus(context.Context, *GetDriverStatusRequest) (*GetDriverStatusResponse, error)
	AssignDriver(context.Context, *AssignDriverRequest) (*AssignDriverResponse, error)
	ValidateID(context.Context, *ValidateIDRequest) (*ValidateIDResponse, error)
	mustEmbedUnimplementedDriverServiceServer()
}

// UnimplementedDriverServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDriverServiceServer struct{}

func (UnimplementedDriverServiceServer) FindAvailableDrivers(context.Context, *FindAvailableDriversRequest) (*FindAvailableDriversResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindAvailableDrivers not implemented")
}
func (UnimplementedDriverServiceServer) ReserveDriver(context.Context, *ReserveDriverRequest) (*ReserveDriverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReserveDriver not implemented")
}
func (UnimplementedDriverServiceServer) ReleaseDriver(context.Context, *ReleaseDriverRequest) (*ReleaseDriverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseDriver not implemented")
}
func (UnimplementedDriverServiceServer) GetDriver(context.Context, *GetDriverRequest) (*GetDriverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDriver not implemented")
}
func (UnimplementedDriverServiceServer) GetDriverStatus(context.Context, *GetDriverStatusRequest) (*GetDriverStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDriverStatus not implemented")
}
func (UnimplementedDriverServiceServer) AssignDriver(context.Context, *AssignDriverRequest) (*AssignDriverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignDriver not implemented")
}
func (UnimplementedDriverServiceServer) ValidateID(context.Context, *ValidateIDRequest) (*ValidateIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateID not implemented")
}
func (UnimplementedDriverServiceServer) mustEmbedUnimplementedDriverServiceServer() {}
func (UnimplementedDriverServiceServer) testEmbeddedByValue()                       {}

// UnsafeDriverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DriverServiceServer will
// result in compilation errors.
type UnsafeDriverServiceServer interface {
	mustEmbedUnimplementedDriverServiceServer()
}

func RegisterDriverServiceServer(s grpc.ServiceRegistrar, srv DriverServiceServer) {
	// If the following call panics, it indicates UnimplementedDriverServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DriverService_ServiceDesc, srv)
}

func _DriverService_FindAvailableDrivers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAvailableDriversRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).FindAvailableDrivers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_FindAvailableDrivers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).FindAvailableDrivers(ctx, req.(*FindAvailableDriversRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_ReserveDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveDriverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).ReserveDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_ReserveDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).ReserveDriver(ctx, req.(*ReserveDriverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_ReleaseDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseDriverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).ReleaseDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_ReleaseDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).ReleaseDriver(ctx, req.(*ReleaseDriverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_GetDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDriverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).GetDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_GetDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).GetDriver(ctx, req.(*GetDriverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_GetDriverStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDriverStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).GetDriverStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_GetDriverStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).GetDriverStatus(ctx, req.(*GetDriverStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_AssignDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignDriverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).AssignDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_AssignDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).AssignDriver(ctx, req.(*AssignDriverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_ValidateID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).ValidateID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_ValidateID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).ValidateID(ctx, req.(*ValidateIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DriverService_ServiceDesc is the grpc.ServiceDesc for DriverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DriverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "driver.DriverService",
	HandlerType: (*DriverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindAvailableDrivers",
			Handler:    _DriverService_FindAvailableDrivers_Handler,
		},
		{
			MethodName: "ReserveDriver",
			Handler:    _DriverService_ReserveDriver_Handler,
		},
		{
			MethodName: "ReleaseDriver",
			Handler:    _DriverService_ReleaseDriver_Handler,
		},
		{
			MethodName: "GetDriver",
			Handler:    _DriverService_GetDriver_Handler,
		},
		{
			MethodName: "GetDriverStatus",
			Handler:    _DriverService_GetDriverStatus_Handler,
		},
		{
			MethodName: "AssignDriver",
			Handler:    _DriverService_AssignDriver_Handler,
		},
		{
			MethodName: "ValidateID",
			Handler:    _DriverService_ValidateID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "driver.proto",
}
