package domain

import "time"

type PaymentStatus string

const (
	PaymentStatusPending PaymentStatus = "pending"
	PaymentStatusAuthorized PaymentStatus = "authorized"
	PaymentStatusCaptureable PaymentStatus = "captureable"
	PaymentStatusCaptured PaymentStatus = "captured"
	PaymentStatusCancelled PaymentStatus = "cancelled"
	PaymentStatusFailed PaymentStatus = "failed"
	PaymentStatusRefunded PaymentStatus = "refunded"
	PaymentStatusRefundPending PaymentStatus = "refund_pending"
)

// PaymentMethod represents the payment method used.
type PaymentMethod string

const (
	PaymentMethodStripe PaymentMethod = "stripe"
	PaymentMethodCash   PaymentMethod = "cash"
	PaymentMethodCard   PaymentMethod = "card"
)

// Payment holds the core payment state and business logic.
type Payment struct {
	ID         string // Generated by snowflake or domain generator
	DeliveryID string
	UserID     string
	Amount     int64 // Amount in minor units (cents)
	Currency   string
	Status     PaymentStatus
	Method     PaymentMethod
	CreatedAt  int64 // Unix timestamp
	UpdatedAt  int64 // Unix timestamp

	// Metadata for tracing and correlation
	CorrelationID string
	CausationID   string

	// Stripe specific
	GatewayPaymentID string
	GatewaySessionID string
}

// NewPayment creates a new payment with pending status.
func NewPayment(deliveryID, userID string, amount int64, currency string, correlationID, causationID string) *Payment {
	return &Payment{
		ID:            generateID(),
		DeliveryID:    deliveryID,
		UserID:        userID,
		Amount:        amount,
		Currency:      currency,
		Status:        PaymentStatusPending,
		Method:        PaymentMethodStripe,
		CreatedAt:     timeNow(),
		UpdatedAt:     timeNow(),
		CorrelationID: correlationID,
		CausationID:   causationID,
	}
}

// Status returns the human-readable status string.
func (p *Payment) StatusString() string {
	return string(p.Status)
}

// CanCapture returns true if the payment can be captured.
func (p *Payment) CanCapture() bool {
	return p.Status == PaymentStatusCaptureable
}

// CanRefund returns true if the payment can be refunded.
func (p *Payment) CanRefund() bool {
	return p.Status == PaymentStatusCaptureable || p.Status == PaymentStatusCaptured
}

// MarkAuthorized marks the payment as authorized.
func (p *Payment) MarkAuthorized() {
	p.Status = PaymentStatusAuthorized
	p.UpdatedAt = timeNow()
}

// MarkCaptureable marks the payment as captureable.
func (p *Payment) MarkCaptureable() {
	p.Status = PaymentStatusCaptureable
	p.UpdatedAt = timeNow()
}

// MarkCaptured marks the payment as captured.
func (p *Payment) MarkCaptured() {
	p.Status = PaymentStatusCaptured
	p.UpdatedAt = timeNow()
}

// MarkCancelled marks the payment as cancelled.
func (p *Payment) MarkCancelled() {
	p.Status = PaymentStatusCancelled
	p.UpdatedAt = timeNow()
}

// MarkFailed marks the payment as failed.
func (p *Payment) MarkFailed() {
	p.Status = PaymentStatusFailed
	p.UpdatedAt = timeNow()
}

// MarkRefunded marks the payment as refunded.
func (p *Payment) MarkRefunded() {
	p.Status = PaymentStatusRefunded
	p.UpdatedAt = timeNow()
}

// IsTerminal returns true if the payment is in a terminal state.
func (p *Payment) IsTerminal() bool {
	switch p.Status {
	case PaymentStatusCancelled, PaymentStatusFailed, PaymentStatusRefunded:
		return true
	default:
		return false
	}
}

// IsCapturable returns true if the payment can be captured.
func (p *Payment) IsCapturable() bool {
	return p.CanCapture()
}

// IsRefundable returns true if the payment can be refunded.
func (p *Payment) IsRefundable() bool {
	return p.CanRefund()
}

// Helper functions
func generateID() string {
	// Use snowflake or simple UUID-like generation
	// In production, use snowflake.Generate()
	now := time.Now().Unix()
	return "pay_" + string(rune('a'+int32(now%26))) +
		string(rune('a'+int32(now%26))) +
		string(rune('0'+int32(now%10))) +
		string(rune('0'+int32(now%10))) +
		string(rune('0'+int32(now%10)))
}