// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: analytics.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyticsService_GetPlatformOverview_FullMethodName  = "/analytics.AnalyticsService/GetPlatformOverview"
	AnalyticsService_GetDriverPerformance_FullMethodName = "/analytics.AnalyticsService/GetDriverPerformance"
)

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Future: gRPC for AI service to query analytics.
// Phase 1 exposes GraphQL only; the gRPC port (50057) is reserved and
// these stubs are pre-generated so later phases can wire a server
// without touching the .proto contract.
type AnalyticsServiceClient interface {
	GetPlatformOverview(ctx context.Context, in *PlatformOverviewRequest, opts ...grpc.CallOption) (*PlatformOverviewResponse, error)
	GetDriverPerformance(ctx context.Context, in *DriverPerformanceRequest, opts ...grpc.CallOption) (*DriverPerformanceResponse, error)
}

type analyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsServiceClient(cc grpc.ClientConnInterface) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) GetPlatformOverview(ctx context.Context, in *PlatformOverviewRequest, opts ...grpc.CallOption) (*PlatformOverviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlatformOverviewResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetPlatformOverview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetDriverPerformance(ctx context.Context, in *DriverPerformanceRequest, opts ...grpc.CallOption) (*DriverPerformanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriverPerformanceResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetDriverPerformance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServiceServer is the server API for AnalyticsService service.
// All implementations must embed UnimplementedAnalyticsServiceServer
// for forward compatibility.
//
// Future: gRPC for AI service to query analytics.
// Phase 1 exposes GraphQL only; the gRPC port (50057) is reserved and
// these stubs are pre-generated so later phases can wire a server
// without touching the .proto contract.
type AnalyticsServiceServer interface {
	GetPlatformOverview(context.Context, *PlatformOverviewRequest) (*PlatformOverviewResponse, error)
	GetDriverPerformance(context.Context, *DriverPerformanceRequest) (*DriverPerformanceResponse, error)
	mustEmbedUnimplementedAnalyticsServiceServer()
}

// UnimplementedAnalyticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticsServiceServer struct{}

func (UnimplementedAnalyticsServiceServer) GetPlatformOverview(context.Context, *PlatformOverviewRequest) (*PlatformOverviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlatformOverview not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetDriverPerformance(context.Context, *DriverPerformanceRequest) (*DriverPerformanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDriverPerformance not implemented")
}
func (UnimplementedAnalyticsServiceServer) mustEmbedUnimplementedAnalyticsServiceServer() {}
func (UnimplementedAnalyticsServiceServer) testEmbeddedByValue()                          {}

// UnsafeAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServiceServer will
// result in compilation errors.
type UnsafeAnalyticsServiceServer interface {
	mustEmbedUnimplementedAnalyticsServiceServer()
}

func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	// If the following call panics, it indicates UnimplementedAnalyticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

func _AnalyticsService_GetPlatformOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatformOverviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetPlatformOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetPlatformOverview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetPlatformOverview(ctx, req.(*PlatformOverviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetDriverPerformance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DriverPerformanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetDriverPerformance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetDriverPerformance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetDriverPerformance(ctx, req.(*DriverPerformanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analytics.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlatformOverview",
			Handler:    _AnalyticsService_GetPlatformOverview_Handler,
		},
		{
			MethodName: "GetDriverPerformance",
			Handler:    _AnalyticsService_GetDriverPerformance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analytics.proto",
}
