// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: analytics.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlatformOverviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformOverviewRequest) Reset() {
	*x = PlatformOverviewRequest{}
	mi := &file_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformOverviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformOverviewRequest) ProtoMessage() {}

func (x *PlatformOverviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformOverviewRequest.ProtoReflect.Descriptor instead.
func (*PlatformOverviewRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *PlatformOverviewRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *PlatformOverviewRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type PlatformOverviewResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TotalDeliveries     int64                  `protobuf:"varint,1,opt,name=total_deliveries,json=totalDeliveries,proto3" json:"total_deliveries,omitempty"`
	CompletedDeliveries int64                  `protobuf:"varint,2,opt,name=completed_deliveries,json=completedDeliveries,proto3" json:"completed_deliveries,omitempty"`
	CompletionRate      float64                `protobuf:"fixed64,3,opt,name=completion_rate,json=completionRate,proto3" json:"completion_rate,omitempty"`
	DataAsOf            string                 `protobuf:"bytes,4,opt,name=data_as_of,json=dataAsOf,proto3" json:"data_as_of,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PlatformOverviewResponse) Reset() {
	*x = PlatformOverviewResponse{}
	mi := &file_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformOverviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformOverviewResponse) ProtoMessage() {}

func (x *PlatformOverviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformOverviewResponse.ProtoReflect.Descriptor instead.
func (*PlatformOverviewResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *PlatformOverviewResponse) GetTotalDeliveries() int64 {
	if x != nil {
		return x.TotalDeliveries
	}
	return 0
}

func (x *PlatformOverviewResponse) GetCompletedDeliveries() int64 {
	if x != nil {
		return x.CompletedDeliveries
	}
	return 0
}

func (x *PlatformOverviewResponse) GetCompletionRate() float64 {
	if x != nil {
		return x.CompletionRate
	}
	return 0
}

func (x *PlatformOverviewResponse) GetDataAsOf() string {
	if x != nil {
		return x.DataAsOf
	}
	return ""
}

type DriverPerformanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverPerformanceRequest) Reset() {
	*x = DriverPerformanceRequest{}
	mi := &file_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverPerformanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverPerformanceRequest) ProtoMessage() {}

func (x *DriverPerformanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverPerformanceRequest.ProtoReflect.Descriptor instead.
func (*DriverPerformanceRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *DriverPerformanceRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *DriverPerformanceRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *DriverPerformanceRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type DriverPerformanceResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DriverId            string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Offers              int64                  `protobuf:"varint,2,opt,name=offers,proto3" json:"offers,omitempty"`
	Accepted            int64                  `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"`
	AcceptanceRate      float64                `protobuf:"fixed64,4,opt,name=acceptance_rate,json=acceptanceRate,proto3" json:"acceptance_rate,omitempty"`
	CompletedDeliveries int64                  `protobuf:"varint,5,opt,name=completed_deliveries,json=completedDeliveries,proto3" json:"completed_deliveries,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DriverPerformanceResponse) Reset() {
	*x = DriverPerformanceResponse{}
	mi := &file_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverPerformanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverPerformanceResponse) ProtoMessage() {}

func (x *DriverPerformanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverPerformanceResponse.ProtoReflect.Descriptor instead.
func (*DriverPerformanceResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *DriverPerformanceResponse) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *DriverPerformanceResponse) GetOffers() int64 {
	if x != nil {
		return x.Offers
	}
	return 0
}

func (x *DriverPerformanceResponse) GetAccepted() int64 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *DriverPerformanceResponse) GetAcceptanceRate() float64 {
	if x != nil {
		return x.AcceptanceRate
	}
	return 0
}

func (x *DriverPerformanceResponse) GetCompletedDeliveries() int64 {
	if x != nil {
		return x.CompletedDeliveries
	}
	return 0
}

var File_analytics_proto protoreflect.FileDescriptor

const file_analytics_proto_rawDesc = "" +
	"\n" +
	"\x0fanalytics.proto\x12\tanalytics\"=\n" +
	"\x17PlatformOverviewRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\"\xbf\x01\n" +
	"\x18PlatformOverviewResponse\x12)\n" +
	"\x10total_deliveries\x18\x01 \x01(\x03R\x0ftotalDeliveries\x121\n" +
	"\x14completed_deliveries\x18\x02 \x01(\x03R\x13completedDeliveries\x12'\n" +
	"\x0fcompletion_rate\x18\x03 \x01(\x01R\x0ecompletionRate\x12\x1c\n" +
	"\n" +
	"data_as_of\x18\x04 \x01(\tR\bdataAsOf\"[\n" +
	"\x18DriverPerformanceRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\"\xc8\x01\n" +
	"\x19DriverPerformanceResponse\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x16\n" +
	"\x06offers\x18\x02 \x01(\x03R\x06offers\x12\x1a\n" +
	"\baccepted\x18\x03 \x01(\x03R\baccepted\x12'\n" +
	"\x0facceptance_rate\x18\x04 \x01(\x01R\x0eacceptanceRate\x121\n" +
	"\x14completed_deliveries\x18\x05 \x01(\x03R\x13completedDeliveries2\xd5\x01\n" +
	"\x10AnalyticsService\x12^\n" +
	"\x13GetPlatformOverview\x12\".analytics.PlatformOverviewRequest\x1a#.analytics.PlatformOverviewResponse\x12a\n" +
	"\x14GetDriverPerformance\x12#.analytics.DriverPerformanceRequest\x1a$.analytics.DriverPerformanceResponseBoZmgithub.com/Omar-Sa6ry/Realtime-Delivery-microservices/services/analytics-service/internal/adapters/grpc/protob\x06proto3"

var (
	file_analytics_proto_rawDescOnce sync.Once
	file_analytics_proto_rawDescData []byte
)

func file_analytics_proto_rawDescGZIP() []byte {
	file_analytics_proto_rawDescOnce.Do(func() {
		file_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)))
	})
	return file_analytics_proto_rawDescData
}

var file_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_analytics_proto_goTypes = []any{
	(*PlatformOverviewRequest)(nil),   // 0: analytics.PlatformOverviewRequest
	(*PlatformOverviewResponse)(nil),  // 1: analytics.PlatformOverviewResponse
	(*DriverPerformanceRequest)(nil),  // 2: analytics.DriverPerformanceRequest
	(*DriverPerformanceResponse)(nil), // 3: analytics.DriverPerformanceResponse
}
var file_analytics_proto_depIdxs = []int32{
	0, // 0: analytics.AnalyticsService.GetPlatformOverview:input_type -> analytics.PlatformOverviewRequest
	2, // 1: analytics.AnalyticsService.GetDriverPerformance:input_type -> analytics.DriverPerformanceRequest
	1, // 2: analytics.AnalyticsService.GetPlatformOverview:output_type -> analytics.PlatformOverviewResponse
	3, // 3: analytics.AnalyticsService.GetDriverPerformance:output_type -> analytics.DriverPerformanceResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_analytics_proto_init() }
func file_analytics_proto_init() {
	if File_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_proto_goTypes,
		DependencyIndexes: file_analytics_proto_depIdxs,
		MessageInfos:      file_analytics_proto_msgTypes,
	}.Build()
	File_analytics_proto = out.File
	file_analytics_proto_goTypes = nil
	file_analytics_proto_depIdxs = nil
}
