// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: protos/media.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolveMediaUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	RequesterId   string                 `protobuf:"bytes,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`        // must equal media.OwnerID
	VersionType   string                 `protobuf:"bytes,3,opt,name=version_type,json=versionType,proto3" json:"version_type,omitempty"`        // "" | "original" | "thumbnail" | "medium" | ...
	ExpirySeconds int32                  `protobuf:"varint,4,opt,name=expiry_seconds,json=expirySeconds,proto3" json:"expiry_seconds,omitempty"` // server caps at 86400
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveMediaUrlRequest) Reset() {
	*x = ResolveMediaUrlRequest{}
	mi := &file_protos_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveMediaUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveMediaUrlRequest) ProtoMessage() {}

func (x *ResolveMediaUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveMediaUrlRequest.ProtoReflect.Descriptor instead.
func (*ResolveMediaUrlRequest) Descriptor() ([]byte, []int) {
	return file_protos_media_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveMediaUrlRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *ResolveMediaUrlRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *ResolveMediaUrlRequest) GetVersionType() string {
	if x != nil {
		return x.VersionType
	}
	return ""
}

func (x *ResolveMediaUrlRequest) GetExpirySeconds() int32 {
	if x != nil {
		return x.ExpirySeconds
	}
	return 0
}

type ResolveMediaUrlResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Url              string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ExpiresAtSeconds int64                  `protobuf:"varint,2,opt,name=expires_at_seconds,json=expiresAtSeconds,proto3" json:"expires_at_seconds,omitempty"`
	ContentType      string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	MediaId          string                 `protobuf:"bytes,4,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Status           string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResolveMediaUrlResponse) Reset() {
	*x = ResolveMediaUrlResponse{}
	mi := &file_protos_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveMediaUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveMediaUrlResponse) ProtoMessage() {}

func (x *ResolveMediaUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveMediaUrlResponse.ProtoReflect.Descriptor instead.
func (*ResolveMediaUrlResponse) Descriptor() ([]byte, []int) {
	return file_protos_media_proto_rawDescGZIP(), []int{1}
}

func (x *ResolveMediaUrlResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ResolveMediaUrlResponse) GetExpiresAtSeconds() int64 {
	if x != nil {
		return x.ExpiresAtSeconds
	}
	return 0
}

func (x *ResolveMediaUrlResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ResolveMediaUrlResponse) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *ResolveMediaUrlResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	RequesterId   string                 `protobuf:"bytes,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"` // must equal media.OwnerID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaRequest) Reset() {
	*x = GetMediaRequest{}
	mi := &file_protos_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaRequest) ProtoMessage() {}

func (x *GetMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaRequest.ProtoReflect.Descriptor instead.
func (*GetMediaRequest) Descriptor() ([]byte, []int) {
	return file_protos_media_proto_rawDescGZIP(), []int{2}
}

func (x *GetMediaRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *GetMediaRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

type GetMediaResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MediaId          string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	OwnerId          string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	FileName         string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ContentType      string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	MediaType        string                 `protobuf:"bytes,5,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Size             int64                  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	Status           string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	ObjectKey        string                 `protobuf:"bytes,8,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	CreatedAtSeconds int64                  `protobuf:"varint,9,opt,name=created_at_seconds,json=createdAtSeconds,proto3" json:"created_at_seconds,omitempty"`
	UpdatedAtSeconds int64                  `protobuf:"varint,10,opt,name=updated_at_seconds,json=updatedAtSeconds,proto3" json:"updated_at_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetMediaResponse) Reset() {
	*x = GetMediaResponse{}
	mi := &file_protos_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaResponse) ProtoMessage() {}

func (x *GetMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaResponse.ProtoReflect.Descriptor instead.
func (*GetMediaResponse) Descriptor() ([]byte, []int) {
	return file_protos_media_proto_rawDescGZIP(), []int{3}
}

func (x *GetMediaResponse) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *GetMediaResponse) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *GetMediaResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *GetMediaResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *GetMediaResponse) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *GetMediaResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetMediaResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetMediaResponse) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *GetMediaResponse) GetCreatedAtSeconds() int64 {
	if x != nil {
		return x.CreatedAtSeconds
	}
	return 0
}

func (x *GetMediaResponse) GetUpdatedAtSeconds() int64 {
	if x != nil {
		return x.UpdatedAtSeconds
	}
	return 0
}

var File_protos_media_proto protoreflect.FileDescriptor

const file_protos_media_proto_rawDesc = "" +
	"\n" +
	"\x12protos/media.proto\x12\x05media\"\xa0\x01\n" +
	"\x16ResolveMediaUrlRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12!\n" +
	"\frequester_id\x18\x02 \x01(\tR\vrequesterId\x12!\n" +
	"\fversion_type\x18\x03 \x01(\tR\vversionType\x12%\n" +
	"\x0eexpiry_seconds\x18\x04 \x01(\x05R\rexpirySeconds\"\xaf\x01\n" +
	"\x17ResolveMediaUrlResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12,\n" +
	"\x12expires_at_seconds\x18\x02 \x01(\x03R\x10expiresAtSeconds\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x19\n" +
	"\bmedia_id\x18\x04 \x01(\tR\amediaId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"O\n" +
	"\x0fGetMediaRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12!\n" +
	"\frequester_id\x18\x02 \x01(\tR\vrequesterId\"\xce\x02\n" +
	"\x10GetMediaResponse\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"media_type\x18\x05 \x01(\tR\tmediaType\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"object_key\x18\b \x01(\tR\tobjectKey\x12,\n" +
	"\x12created_at_seconds\x18\t \x01(\x03R\x10createdAtSeconds\x12,\n" +
	"\x12updated_at_seconds\x18\n" +
	" \x01(\x03R\x10updatedAtSeconds2\x9d\x01\n" +
	"\fMediaService\x12P\n" +
	"\x0fResolveMediaUrl\x12\x1d.media.ResolveMediaUrlRequest\x1a\x1e.media.ResolveMediaUrlResponse\x12;\n" +
	"\bGetMedia\x12\x16.media.GetMediaRequest\x1a\x17.media.GetMediaResponseBiZggithub.com/Omar-Sa6ry/Realtime-Delivery-microservices/services/media-service/internal/transport/grpc/pbb\x06proto3"

var (
	file_protos_media_proto_rawDescOnce sync.Once
	file_protos_media_proto_rawDescData []byte
)

func file_protos_media_proto_rawDescGZIP() []byte {
	file_protos_media_proto_rawDescOnce.Do(func() {
		file_protos_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_media_proto_rawDesc), len(file_protos_media_proto_rawDesc)))
	})
	return file_protos_media_proto_rawDescData
}

var file_protos_media_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_media_proto_goTypes = []any{
	(*ResolveMediaUrlRequest)(nil),  // 0: media.ResolveMediaUrlRequest
	(*ResolveMediaUrlResponse)(nil), // 1: media.ResolveMediaUrlResponse
	(*GetMediaRequest)(nil),         // 2: media.GetMediaRequest
	(*GetMediaResponse)(nil),        // 3: media.GetMediaResponse
}
var file_protos_media_proto_depIdxs = []int32{
	0, // 0: media.MediaService.ResolveMediaUrl:input_type -> media.ResolveMediaUrlRequest
	2, // 1: media.MediaService.GetMedia:input_type -> media.GetMediaRequest
	1, // 2: media.MediaService.ResolveMediaUrl:output_type -> media.ResolveMediaUrlResponse
	3, // 3: media.MediaService.GetMedia:output_type -> media.GetMediaResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_media_proto_init() }
func file_protos_media_proto_init() {
	if File_protos_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_media_proto_rawDesc), len(file_protos_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_media_proto_goTypes,
		DependencyIndexes: file_protos_media_proto_depIdxs,
		MessageInfos:      file_protos_media_proto_msgTypes,
	}.Build()
	File_protos_media_proto = out.File
	file_protos_media_proto_goTypes = nil
	file_protos_media_proto_depIdxs = nil
}
