import { Permission, Role } from "./enum.constant";

export const rolePermissionsMap: Record<Role, Permission[]> = {
  [Role.ADMIN]: [
    Permission.UPDATE_USER,
    Permission.DELETE_USER,
    Permission.EDIT_USER_ROLE,
    Permission.RESET_PASSWORD,
    Permission.CHANGE_PASSWORD,
    Permission.FORGOT_PASSWORD,
    Permission.LOGOUT,
    Permission.VIEW_USER,
    Permission.RECHARGE_WALLET,
    Permission.READ_NOTIFICATION,
    Permission.UPDATE_NOTIFICATION,
    Permission.DELETE_NOTIFICATION,
    Permission.MANAGE_NOTIFICATION_PREFERENCES,
    Permission.CREATE_DELIVERY,
    Permission.VIEW_DELIVERY,
    Permission.UPDATE_DELIVERY_STATUS,
    Permission.CANCEL_DELIVERY,
    Permission.ASSIGN_DELIVERY_DRIVER,
  ],
  [Role.USER]: [
    Permission.UPDATE_USER,
    Permission.RESET_PASSWORD,
    Permission.CHANGE_PASSWORD,
    Permission.FORGOT_PASSWORD,
    Permission.LOGOUT,
    Permission.RECHARGE_WALLET,
    Permission.READ_NOTIFICATION,
    Permission.UPDATE_NOTIFICATION,
    Permission.MANAGE_NOTIFICATION_PREFERENCES,
    Permission.CREATE_DELIVERY,
    Permission.VIEW_DELIVERY,
    Permission.CANCEL_DELIVERY,
  ],
  [Role.DRIVER]: [
    Permission.UPDATE_USER,
    Permission.RESET_PASSWORD,
    Permission.CHANGE_PASSWORD,
    Permission.FORGOT_PASSWORD,
    Permission.LOGOUT,
    Permission.READ_NOTIFICATION,
    Permission.UPDATE_NOTIFICATION,
    Permission.MANAGE_NOTIFICATION_PREFERENCES,
    Permission.VIEW_DELIVERY,
    Permission.UPDATE_DELIVERY_STATUS,
    Permission.ASSIGN_DELIVERY_DRIVER,
  ],
};
