# Get the profile of the currently logged-in user (requires Bearer token) (user)
query {
  myProfile {
    statusCode
    message
    success
    data {
      id
      firstName
      lastName
      email
      role
      phoneNumber
      createdAt
    }
  }
}

# Get a specific user by their ID (Admin only) (admin)
query {
  user(id: "01KPJSGYC1XNRH3DP7Y1D20CDP") {
    statusCode
    message
    success
    data {
      id
      firstName
      lastName
      email
      role
      createdAt
    }
  }
}

# Update the profile of the currently logged-in user (requires Bearer token) (user)
mutation {
  updateProfile(
    input: {
      firstName: "Ahmed"
      lastName: "Sabry"
    }
  ) {
    statusCode
    message
    success
    data {
      id
      firstName
      lastName
      email
      role
      phoneNumber
      createdAt
    }
  }
}

# Promote a user to Admin (Admin only) (admin)
mutation {
  promoteUserToAdmin(id: "01KPJSGYC1XNRH3DP7Y1D20CDP") {
    statusCode
    message
    success
  }
}

# Toggle user active status (Admin only) (admin)
mutation {
  toggleUserActive(id: "01KPJSGYC1XNRH3DP7Y1D20CDP", isActive: false) {
    statusCode
    message
    success
  }
}

# Delete a user (Admin only) (admin)
mutation {
  deleteUser(id: "01KPJSGYC1XNRH3DP7Y1D20CDP") {
    statusCode
    message
    success
  }
}

# Add a new address to user profile (requires Bearer token) (user)
mutation {
  addAddress(
    input: {
      title: "Home"
      street: "El-Galaa Street"
      city: "Cairo"
      state: "Cairo Governorate"
      postalCode: "11511"
      isDefault: true
    }
  ) {
    statusCode
    message
    success
    data {
      id
      title
      street
      city
      state
      postalCode
      isDefault
    }
  }
}

# Delete an address from user profile (requires Bearer token) (user)
mutation {
  deleteAddress(addressId: "01KPJSGYC1XNRH3DP7Y1D20CDP") {
    statusCode
    message
    success
  }
}

# Set an address as default (requires Bearer token) (user)
mutation {
  setDefaultAddress(addressId: "01KPJSGYC1XNRH3DP7Y1D20CDP") {
    statusCode
    message
    success
  }
}

# Retrieve currently logged-in user's addresses (requires Bearer token) (user)
query {
  myAddresses {
    statusCode
    message
    success
    data {
      id
      title
      street
      city
      state
      postalCode
      isDefault
      createdAt
    }
  }
}
